-- begin EDUCATION_LEGAL_PERSON
alter table EDUCATION_LEGAL_PERSON add constraint FK_EDUCATION_LEGAL_PERSON_ON_BANK foreign key (BANK_ID) references EDUCATION_BANK(ID)^
create unique index IDX_EDUCATION_LEGAL_PERSON_UNIQ_NAME_OF_COMPANY on EDUCATION_LEGAL_PERSON (NAME_OF_COMPANY) ^
create unique index IDX_EDUCATION_LEGAL_PERSON_UNIQ_PERSONAL_ACCOUNT on EDUCATION_LEGAL_PERSON (PERSONAL_ACCOUNT) ^
create unique index IDX_EDUCATION_LEGAL_PERSON_UNIQ_INN on EDUCATION_LEGAL_PERSON (INN) ^
create index IDX_EDUCATION_LEGAL_PERSON_ON_BANK on EDUCATION_LEGAL_PERSON (BANK_ID)^
-- end EDUCATION_LEGAL_PERSON
-- begin EDUCATION_CONTRACT
alter table EDUCATION_CONTRACT add constraint FK_EDUCATION_CONTRACT_ON_CUSTOMER foreign key (CUSTOMER_ID) references EDUCATION_CUSTOMER(ID)^
create unique index IDX_EDUCATION_CONTRACT_UNIQ_NUMBER_ on EDUCATION_CONTRACT (NUMBER_) ^
create index IDX_EDUCATION_CONTRACT_ON_CUSTOMER on EDUCATION_CONTRACT (CUSTOMER_ID)^
-- end EDUCATION_CONTRACT
-- begin EDUCATION_CUSTOMER
create unique index IDX_EDUCATION_CUSTOMER_UNIQ_PERSONAL_ACCOUNT on EDUCATION_CUSTOMER (PERSONAL_ACCOUNT) ^
-- end EDUCATION_CUSTOMER
-- begin EDUCATION_BANK
create unique index IDX_EDUCATION_BANK_UNIQ_BIK on EDUCATION_BANK (BIK) ^
create unique index IDX_EDUCATION_BANK_UNIQ_NAME on EDUCATION_BANK (NAME) ^
-- end EDUCATION_BANK
-- begin EDUCATION_PHYSICAL_PERSON
create unique index IDX_EDUCATION_PHYSICAL_PERSON_UNIQ_PERSONAL_ACCOUNT on EDUCATION_PHYSICAL_PERSON (PERSONAL_ACCOUNT) ^
-- end EDUCATION_PHYSICAL_PERSON
